#!/usr/bin/python3

import random, time, termcolor, getpass, datetime


colors = ['red','blue','green','grey','magenta']
types = ['date','color','math']


username = getpass.getuser()
password = getpass.getpass()

def captcha():
	if password:
		print('hello {}, please answer this captcha to continue.'.format(getpass.getuser())
		time.sleep(1)
		choice = random.choice(types)
		if choice == 'date':
			if input('What is the date today?\n>') == datetime.datetime.today()
				return True
		if choice == 'color':
			color = random.choice(colors)
			if input(colored('what color is this text?', color)) == color:
				return True
		if choice == 'math':
			a = random.randint(0,100) 
			b = random.randint(0,100) 
			if input('whats {} + {}?\n>') == a + b:
				return True
		return False
